env:
  global:
  # Docker Repository
  - REPO=fjudith/wordpress
  # Compute docker tag
  - TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH}-fpm ; fi`
  - PHP5=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "php5-fpm"; else echo ${TRAVIS_BRANCH}-php5-fpm ; fi`
  - PHP7=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "php7-fpm"; else echo ${TRAVIS_BRANCH}-php7-fpm ; fi`
  - NGINX=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "nginx"; else echo ${TRAVIS_BRANCH}-nginx ; fi`
  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "2KBo0owyPc448YMOA5LLemAejzZ64JoUAD0HseZkYQvme0jsniuG7s5rYNXWQuxmI9AJLGUTTpW7UaH3OXvBCbFvoZpfcxiy+tu3E5W0k6muOkQkz/T6gNqeCoyVNJNXoDwkBQ2KJZ017nE02r6RWGVeJDXTl69TkcabHWuyDpf/RVhZfaOzjP4j/138qKYb3Ss2TYXrHjQJ0M66QZAUeNx5xfVcCDUIB1ofnSLgV2+l/doCNElHMkIeY1H7k5LHwgrm/ROB2tVFNFZqPDpSD7kgn9vqtiNeb/iQOmfGdD3F40H0gZYR38UuF81mTLsM/tG7SIYIAwxHgboMQNk+3VqRTYLGcNOPx7V/WagRIWJ8zQDMwYan9b/TxXJh5K+STViu12jYXKoLQae9M6sEs32VEFmk7kZ2YqEGOiePd4fXNaBCgHKB6GRKESJ6osQMran+UJM7wrIgmMTiBus849hR1RJTbRNU5Mcge7z9dLigACBmFICl7ZxzZ/1M/8x+4jSuEltaph+isKizyxbxm0cpVoJtD8fm7NyZByqLvSt6TQ2iiGljEJIBhgd8B2K+kRkFzOLbBh6jzhAF2BHa4nBr/irirkfhUvLX/vtKBWUhN0ojeBDHbZUwjcYFEom7V0kb/2Zx2MjfeAORwDbTe92KeO9nvmV160ASU5Iolok="
  - secure: "rLhPLS9ZvT0kovidLhouHGhoNK2jZKPP9h6om4QPlwtUuVRnMG1HOwZV6RnUkdTAZUkhvLeAk+3atHObtDaTi86yqBIPyi4cjoF8y5QV4BEJmZcpNs9ECWJRHpeYjJqY1lrGCnxBnSMR5ldI55FR+jtVo9PbARrDuIcwOf+irQ39nG+NRPqYfNjo4TG1QWQdqfF6HOIkOU9BTexy2blbOOEDpinh8U+v9tiqh6aToLP/t8B2aY9NP1Mn6MHQK2ALdk79RDjzgjNsm7A/h+Os9CW3CBwYpK/EVhZjYo46ebu/G++JmWjUJW1VamMHJLILoRVWhxgW1CQTKhABYL0di7xEhz6Ose6NQWAS4wCe42so7o1U/AgoavyzKO1kk9q9f7zFS8BXlDgiu2dbtNUMa4uj/g3EcsVDzx7W6pctq6Mx1KrsytaG3065qBbPnRrN20HWY3DyODL4Tq+iDcWiqpYbQMQaYPNALg7N3iC1R+iUmbwd2TqmXvKtDz5Z5spWXyqw+jEoxQ1YL5DIUbquUHDUjwGAX7OBSgD5cAjrjd8PBMt2qGmbAsE/mb0akmbP19Sfn+wjyUvKJ2FjIONEuZX3+0LUFHmbbt2EzWho7BmeON9WJcqziAvJwc6FJy9u9RQa4VkhPsY5f0IeCdUhmJ3kcnH5gk6DSMnPhcYWqQs="
  - secure: "SDKcuwki9nA/x8f5dI8Jexd7b/eWptr9lAnIABLiI4uY9/px+OW7dHue8031pXME7fACnxGB8WdN6D+H4OnWAuVdj0KN7iFoMON2O+Hjw7MzVYGZ+z7XgJUAz59HVt8u/75cnG+7176v98TThk8x+CSE0AA6jPBk/VrrSwmD7mDoI0H2KgVPxVs9S5Zn6cvo50Rk/7dhiKl/LaDT0UdBsGOGDf1QxYyI7cRsO2kyDZZxOV2SUqr4+f2m03Qdi8EyNGihc50PgzUd2A3b8yyQ0cKpZmy6zBNf4bXGMxfKmaF4AbzY++Ge9D3yMUEoa3r9kkilqSikXcjUEfRgOoejHzWy6W0xdaV4Ya6nE3BkLBFEwzG6ykI+CMi6TsYzMKlFD2RYoJh6iji4jaUfxTsbkrNbw0ocZ+tJPLPg3YWg1cgcEM60Yc5YXKyM7RsXaQGITD2hi0CCR3o1P9oZmpKdqk6y3v0+mGcuk+mw49EzdAFgEZ/DYWrQgsXDvE1DZPcFaHBSqfYParyBU7ejFrKPzqxp63qU7uaSHb9q+v9BdBjphuoGDSFvxn6ARcXBdc+cSbewV7t7GK4IdfcdfyNdfrBJZkrtFvSDwEGJwx3hO+Fp109pmDNkaRXADVwdFvJbvehyx634SjKh9H5Qqsq6Nx8Tsu2TK4Ca1XPrGTCRIqs="


sudo: required
services:
  - docker


before_install:
  # BUILD
  #
  # php5-fpm: build
  - docker build -f php5-fpm/Dockerfile -t ${REPO}:${COMMIT}-php5-fpm php5-fpm/
  # php7-fpm: build
  - docker build -f php7-fpm/Dockerfile -t ${REPO}:${COMMIT}-php7-fpm php7-fpm/
  # nginx: build
  - docker build -f nginx/Dockerfile -t ${REPO}:${COMMIT}-nginx nginx/
  # RUN
  #
  ## php5: mariadb
  - docker run -d --name "php5-md-${TRAVIS_BUILD_NUMBER}" -e MYSQL_DATABASE=wordpress -e MYSQL_ROOT_PASSWORD=Ch4ng3m3 -e MYSQL_USER=wordpress -e MYSQL_PASSWORD=Ch4ng3m3 mariadb
  ## php5: memcached
  - docker run -d --name "php5-mc-${TRAVIS_BUILD_NUMBER}" memcached
  ## php5: fpm
  - sleep 15
  - docker run -d --name "php5-fpm-${TRAVIS_BUILD_NUMBER}" -v php5-data:/var/www/html --link php5-mc-${TRAVIS_BUILD_NUMBER}:memcached --link php5-md-${TRAVIS_BUILD_NUMBER}:mysql ${REPO}:${COMMIT}-php5-fpm
  ## php5: nginx
  - docker run -d --name "php5-nginx-${TRAVIS_BUILD_NUMBER}" -v php5-data:/var/www/html --link php5-mc-${TRAVIS_BUILD_NUMBER}:memcached --link php5-fpm-${TRAVIS_BUILD_NUMBER}:wordpress  ${REPO}:${COMMIT}-nginx
  ## php7: mariadb
  - docker run -d --name "php7-md-${TRAVIS_BUILD_NUMBER}" -e MYSQL_DATABASE=wordpress -e MYSQL_ROOT_PASSWORD=Ch4ng3m3 -e MYSQL_USER=wordpress -e MYSQL_PASSWORD=Ch4ng3m3 mariadb
  ## php7: memcached
  - docker run -d --name "php7-mc-${TRAVIS_BUILD_NUMBER}" memcached
  ## php7: fpm
  - sleep 15
  - docker run -d --name "php7-fpm-${TRAVIS_BUILD_NUMBER}" -v php7-data:/var/www/html --link php7-mc-${TRAVIS_BUILD_NUMBER}:memcached --link php7-md-${TRAVIS_BUILD_NUMBER}:mysql ${REPO}:${COMMIT}-php7-fpm
  ## php7: nginx
  - docker run -d --name "php7-nginx-${TRAVIS_BUILD_NUMBER}" -v php7-data:/var/www/html --link php7-mc-${TRAVIS_BUILD_NUMBER}:memcached --link php7-fpm-${TRAVIS_BUILD_NUMBER}:wordpress  ${REPO}:${COMMIT}-nginx


script:
  # php5: test
  - docker run --rm --link php5-nginx-${TRAVIS_BUILD_NUMBER}:nginx phusion/baseimage /bin/bash -c "curl -ik -L http://nginx:80"
  # php7: test
  - docker run --rm --link php7-nginx-${TRAVIS_BUILD_NUMBER}:nginx phusion/baseimage /bin/bash -c "curl -ik -L http://nginx:80"


after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  # latest
  - docker tag ${REPO}:${COMMIT}-php5-fpm ${REPO}:${TAG}
  # php5
  - docker tag ${REPO}:${COMMIT}-php5-fpm ${REPO}:${PHP5}
  - docker tag ${REPO}:${COMMIT}-php5-fpm ${REPO}:travis-${TRAVIS_BUILD_NUMBER}-php5-fpm
  # php7
  - docker tag ${REPO}:${COMMIT}-php7-fpm ${REPO}:${PHP7}
  - docker tag ${REPO}:${COMMIT}-php7-fpm ${REPO}:travis-${TRAVIS_BUILD_NUMBER}-php7-fpm
  # nginx
  - docker tag ${REPO}:${COMMIT}-nginx ${REPO}:${NGINX}
  - docker tag ${REPO}:${COMMIT}-nginx ${REPO}:travis-${TRAVIS_BUILD_NUMBER}-nginx
  - docker push ${REPO}