env:
  global:
  # Docker Repository
  - REPO=fjudith/wordpress
  # Compute docker tag
  - TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH}-fpm ; fi`
  - PHP5=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "php5-fpm"; else echo ${TRAVIS_BRANCH}-php5-fpm ; fi`
  - PHP7=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "php7-fpm"; else echo ${TRAVIS_BRANCH}-php7.1-fpm ; fi`
  - NGINX=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "nginx"; else echo ${TRAVIS_BRANCH}-nginx ; fi`
  - CLI=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "cli"; else echo ${TRAVIS_BRANCH}-cli ; fi`
  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "LJFLXYSH+zgiCphNAWyapVqyLzbG7jSh8ff5GWEOMzEe6jPxqdJ0lZnKRmTKf+NnTuzdZF3bHC37iR62MHJyx86jOO3UoKDDh1WVZvBpS1yooQuEtS2d65ErikdCbfIMklyz7nFBTKKHonjasL0IzMValva3SANLJ/9av4Vgj+p970iiOs7EyJHIEAW11VdPNE3d1NdfjlmkDGKkUwgkOyVMoM4lxqkmL3HsjtV+OazdKJRD6pYxd0MWczj2lYcRnL/EMqZU32/lqqx0NY5KX/tJXs69zZKjf8XJFDKEbOd2IjxOrie8swmk2Ecd2LRV8PywJgxx8M8qeyKPH3BDFTIYO8h7OKJCzPscE0TMzaSuOLiOSFYggJk7onhxgrs+6coufVbDPcyPWTzp/p6gm/74ARe0NMLo4EbJt43U4bFrukqRI8j0Mpc4peqjuK9aFTsLh/quJ4dVvbIgXjAOk/M8adfxUfwZbHRq/QtrYSuwdZcH0UunSjsuhSnbg0/slcEmAhyzaGOkNudrKTq7I01wzs5/lRQxR1/BqQGxwLjYc1blvpz+cywJa+haz8iGqAdiFIcLfHFHiGp+c0MgLvIKE0ZADov/VFXBLtUiWWvXpMD2tlv0IpgyW258wI4SC+C+3UhKfw7SlnzKsgdbLbpUckPcgC+UAQYD687vpkc="
  - secure: "udzoHkWjvBOmxObD6bY7trVshjwXWr19efLpf/Wytbv3sK9CcTrtLDYUplZ6pX3X1ApHYURosfTrWDvPBiz+5+uRtmEcN2y3i4XjvujPRwD7TD8HnkG23BrazVUWU/bLbTjwkNICepMAos+/WHABeWGD0SI9xm72F0Ie3ozy+bqG+b/gNV6+MpowP1lZF2ObJt3IsZ0Im4Tf/CX51nC1Vt4qI4CPAoxhzn6bJiK8iJpjwkCBUNCO25Qa3ZKKX56z2WzDBl/VYH5SHnfJ0RLvd2VIlI24fEX6TjemI5HCtNc6em3Gmnr7S3u7C6+n8magAjL8tGwxT5571vGzXc4Ge/sxorMNqwUhRL9fHkOBo+iWSB8816eLugIk7J3oCMH7tCs+Nwg10dzMtC6buq8eqB7naXwP5FN2jl2PSKnbtyhHRo1+TTB2yrjV1wRziSzGMLB/kpmu78wiU0CRs/P7DwkJY2iWhHzp4B3W3WTOeQJLSu8NH2DmoqfD6/g33Yda8A2OUG8wS6H7DsAreGVmToZqYqmN3SIRrmnk9t0FWk5uykAFJzqxuIgotiDD1KJmIkfOKtdU432A+zeey4TQBu+sb8uYBmehv7u1gD+6KUEVHUD++gvTvLd95Eiot2YeRGgoa8Cczt5EYeSBTNtuy0nx5yHbs0MA/bsLTY+ask4="
  - secure: "cDgjQYFSHnKZCfuIfp4VJfUTrowvSmVV9h18L5ybz/1TtYvv+ctZfbmf8MTLKZRnD27vmLUOobXfvPb1MnN736fc1umVt9MRWfrGjZKkQ1bK2k6bSJrcJhNOY1qCVub4EvTxd53sEkx61pdSXyHuau35anmQcFkCRHMXXnibMUJs+8yGVKMr0i4y7baLwSw5PAfPqA9csEmtkZRx4Z5X6zEyj57ArnGYbE+TTd4eT8M3X9GKF9Jwp4LXWLQSJvLgPCMo9ogmQ72eFn6TP+aa0ikRtXwExXmVZjsdMXD2fBh5ONFnbnVe2isfZse/xmVePdbYfMAaMXoLJADhi7SnJQtf7A5eKJ0Z/DRfEzU/nIMP2jrYuuEDAoX3P9HPlzeAloTn8f+QooAP/4WcQ/ZhqzpE88NFDG2rA+TkAQU19VwOju6ucCCVQfiVultku7mZE7I5b1FcBc3C7/Aeo4LPdw5IlEYvP+abhUBgs6gZs/ZtaENL9zSxWdSkuqFHRQKf/oIwD8Hs6sBkxg31WVaor73SyjWQaX6eCLHeLFg0lLGHph+2WEqhiK29GX2Rp/H3k31YVA4S5iOAvqGVYSLkvvx4b2PLObJKXfy3Qu+QAxJLRSIayPFI073fplcW8RZKjRsig0wORByGhL0cIPugd6qk/bC8/n0I+Blneln9s1c="


sudo: required
services:
  - docker


before_install:
  # BUILD
  #
  # php5-fpm: build
  - docker build -f php5-fpm/Dockerfile -t ${REPO}:${COMMIT}-php5-fpm php5-fpm/
  # php7-fpm: build
  - docker build -f php7-fpm/Dockerfile -t ${REPO}:${COMMIT}-php7-fpm php7-fpm/
  # nginx: build
  - docker build -f nginx/Dockerfile -t ${REPO}:${COMMIT}-nginx nginx/
  # nginx: cli
  - docker build -f cli/Dockerfile -t ${REPO}:${COMMIT}-cli cli/
  # RUN
  #
  ## php5: mariadb
  - docker run -d --name "php5-md-${TRAVIS_BUILD_NUMBER}" -e MYSQL_DATABASE=wordpress -e MYSQL_ROOT_PASSWORD=Ch4ng3m3 -e MYSQL_USER=wordpress -e MYSQL_PASSWORD=Ch4ng3m3 mariadb
  ## php5: memcached
  - docker run -d --name "php5-mc-${TRAVIS_BUILD_NUMBER}" memcached
  ## php5: fpm
  - sleep 15
  - docker run -d --name "php5-fpm-${TRAVIS_BUILD_NUMBER}" -v php5-data:/var/www/html --link php5-mc-${TRAVIS_BUILD_NUMBER}:memcached --link php5-md-${TRAVIS_BUILD_NUMBER}:mysql ${REPO}:${COMMIT}-php5-fpm
  ## php5: nginx
  - docker run -d --name "php5-nginx-${TRAVIS_BUILD_NUMBER}" -v php5-data:/var/www/html --link php5-mc-${TRAVIS_BUILD_NUMBER}:memcached --link php5-fpm-${TRAVIS_BUILD_NUMBER}:wordpress  ${REPO}:${COMMIT}-nginx
  ## php7: mariadb
  - docker run -d --name "php7-md-${TRAVIS_BUILD_NUMBER}" -e MYSQL_DATABASE=wordpress -e MYSQL_ROOT_PASSWORD=Ch4ng3m3 -e MYSQL_USER=wordpress -e MYSQL_PASSWORD=Ch4ng3m3 mariadb
  ## php7: memcached
  - docker run -d --name "php7-mc-${TRAVIS_BUILD_NUMBER}" memcached
  ## php7: fpm
  - sleep 15
  - docker run -d --name "php7-fpm-${TRAVIS_BUILD_NUMBER}" -v php7-data:/var/www/html --link php7-mc-${TRAVIS_BUILD_NUMBER}:memcached --link php7-md-${TRAVIS_BUILD_NUMBER}:mysql ${REPO}:${COMMIT}-php7-fpm
  ## php7: nginx
  - docker run -d --name "php7-nginx-${TRAVIS_BUILD_NUMBER}" -v php7-data:/var/www/html --link php7-mc-${TRAVIS_BUILD_NUMBER}:memcached --link php7-fpm-${TRAVIS_BUILD_NUMBER}:wordpress  ${REPO}:${COMMIT}-nginx
  ## php7: cli
  - docker run -d --name "php7-cli-${TRAVIS_BUILD_NUMBER}" -v php7-data:/var/www/html --link php7-md-${TRAVIS_BUILD_NUMBER}:mysql  ${REPO}:${COMMIT}-cli


script:
  # php5: test
  - docker run --rm --link php5-nginx-${TRAVIS_BUILD_NUMBER}:nginx phusion/baseimage /bin/bash -c "curl -ik -L http://nginx:80"
  # php7: test
  - docker run --rm --link php7-nginx-${TRAVIS_BUILD_NUMBER}:nginx phusion/baseimage /bin/bash -c "curl -ik -L http://nginx:80"


after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  # latest
  - docker tag ${REPO}:${COMMIT}-php5-fpm ${REPO}:${TAG}
  # php5
  - docker tag ${REPO}:${COMMIT}-php5-fpm ${REPO}:${PHP5}
  - docker tag ${REPO}:${COMMIT}-php5-fpm ${REPO}:travis-${TRAVIS_BUILD_NUMBER}-php5-fpm
  # php7
  - docker tag ${REPO}:${COMMIT}-php7-fpm ${REPO}:${PHP7}
  - docker tag ${REPO}:${COMMIT}-php7-fpm ${REPO}:travis-${TRAVIS_BUILD_NUMBER}-php7-fpm
  # nginx
  - docker tag ${REPO}:${COMMIT}-nginx ${REPO}:${NGINX}
  - docker tag ${REPO}:${COMMIT}-nginx ${REPO}:travis-${TRAVIS_BUILD_NUMBER}-nginx
  # cli
  - docker tag ${REPO}:${COMMIT}-cli ${REPO}:${CLI}
  - docker tag ${REPO}:${COMMIT}-cli ${REPO}:travis-${TRAVIS_BUILD_NUMBER}-cli
  # push to public registry
  - docker push ${REPO}